#factory.setHost("192.168.13.45");
#factory.setPort(5672);
#factory.setVirtualHost("/tianyu");
#factory.setUsername("root");
#factory.setPassword("root");
spring:
  rabbitmq:
    host: 192.168.13.45
    port: 5672
    username: root
    password: root
    virtual-host: /tianyu